name: ghbuild

permissions: write-all
on:
  push:
    branches-ignore:
      - 'gh-pages'
  workflow_dispatch:

jobs:
  call_build:
    uses: TEHIK-EE/smart-base/.github/workflows/ghbuild.yml@main
    with:
      TX_SERVER: "https://term.tehik.ee/fhir/"
